# Generated by Django 4.0 on 2021-12-26 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player_Level',
            fields=[
                ('id_player_level', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=22)),
                ('minimum_goal_scored', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id_team', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=22)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id_player', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=22)),
                ('goal_scored', models.IntegerField()),
                ('salary', models.FloatField()),
                ('bonus', models.FloatField()),
                ('complete_salary', models.FloatField()),
                ('player_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_level', to='core.player_level')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team', to='core.team')),
            ],
        ),
    ]
