# Generated by Django 4.0 on 2021-12-27 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='Player_Level',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
