# Generated by Django 4.0 on 2021-12-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='complete_salary',
            field=models.FloatField(null=True),
        ),
    ]
